name: Deploy backend
on:
  push:
    branches: [ main ]
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            cd /var/www/finance-app-wm
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/szymon-gh
            git pull origin main
            cd ./backend
            echo ${{secrets.BACKEND_DEV}} > .env
            bash start_container.sh
      - name: Wait for docker to finish building
        run: sleep 30
