name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          cd /var/www/finance-app-wm
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/szymon-gh
          git pull origin ,aom
          cd ./backend
          bash start_container.sh
