name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          cd /var/www/finance-app-wm
          git pull origin main
          git status
          cd ./backend
          docker compose -f docker-compose.yml up --build
